# Generated by Django 4.2 on 2024-04-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='文章标题')),
                ('author', models.CharField(blank=True, max_length=20, verbose_name='作者')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='内容摘要')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'db_table': 'blog_document_content',
            },
        ),
    ]
