# Generated by Django 4.2 on 2024-04-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcontent',
            name='summary',
            field=models.TextField(blank=True, max_length=500, verbose_name='内容摘要'),
        ),
    ]
